export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_TRANSACTION_ID = "SET_TRANSACTION_ID";
export const SET_REFERENCE_NO = "SET_REFERENCE_NO";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
